import { json } from "@sveltejs/kit";

export async function GET({ params, request }) {
    const color = params.color;
    const accessToken = request.headers.get("Access-Token");
    const songs = request.headers.get("Songs")!;

    let res;
    let data;

    res = await fetch(`https://api.spotify.com/v1/me`, {
        method: "GET",
        headers: {
            "Authorization": `Bearer ${accessToken}`,
        },
    });
    data = await res.json();
    const userID = data.id;

    res = await fetch(`https://api.spotify.com/v1/users/${userID}/playlists`, {
        method: "POST",
        body: JSON.stringify({
            "name": color,
            "description": "generated by chromatica",
            "public": false,
        }),
        headers: {
            "Authorization": `Bearer ${accessToken}`,
        },
    });
    data = await res.json();
    const playlistID = data.id;
    const playlistURL = data.external_urls.spotify;

    await fetch(`https://api.spotify.com/v1/playlists/${playlistID}/tracks`, {
        method: "POST",
        body: JSON.stringify({
            "uris": songs.split(";"),
        }),
        headers: {
            "Authorization": `Bearer ${accessToken}`,
        },
    })

    return json(playlistURL);
}
