import { json } from "@sveltejs/kit";
import _ from "lodash";

export async function GET({ params, request }) {
    const color = params.color;
    const id = params.id;
    const accessToken = request.headers.get("Access-Token");
    const songs = request.headers.get("Songs")!.split(";");

    let res;
    let data;

    res = await fetch(`https://api.spotify.com/v1/me`, {
        method: "GET",
        headers: {
            "Authorization": `Bearer ${accessToken}`,
        },
    });
    data = await res.json();
    const userID = data.id;

    res = await fetch(`https://api.spotify.com/v1/users/${userID}/playlists`, {
        method: "POST",
        body: JSON.stringify({
            "name": color,
            "description": `${color} playlist for ${id} generated by chromatica`,
            "public": false,
        }),
        headers: {
            "Authorization": `Bearer ${accessToken}`,
        },
    });
    data = await res.json();
    const playlistID = data.id;
    const playlistURL = data.external_urls.spotify;

    const chunkedSongs = _.chunk(songs, 100);

    chunkedSongs.forEach(async (s, i) => {
        console.log(`adding songs ${i}`);
        await fetch(`https://api.spotify.com/v1/playlists/${playlistID}/tracks`, {
            method: "POST",
            body: JSON.stringify({
                "uris": s,
            }),
            headers: {
                "Authorization": `Bearer ${accessToken}`,
            },
        });
    });


    return json(playlistURL);
}
